### ISSUE TITLE
Investigate optional use in kernel

### ISSUE THREAD

**Issue by harloff-g** [googleinterns/scsi2nvme#71]
The use of std::optional in kernel-space must be confirmed, as the translation library currently uses this type

**Comment by eyhhuang** [comment]
If std::optional isn't automatically supposed in the kernel space, I feel like it might be worthwhile to write our own optional struct/wrapper instead of discarding the use of optionals altogether. optionals give a clear way to indicate that the value has been initialized and I think that can protect us from some accidents and make the code more readable.

**Comment by harloff-g** [comment]
@eyhhuang good point! I imagine we can provide a less feature-rich optional class with relative ease.

As for updates on this issue, it seems optional does not link correctly without some third-party modifications. Specifically, issues arise in optional's dependency on limits.h in the c++ standard.

limits.h has a number of functions that do not agree with register use in the kernel space. Detailed build errors are found below:

`/usr/include/c++/9/limits: In static member function ‘static constexpr float std::numeric_limits<float>::min()’:`
`/usr/include/c++/9/limits:1665:35: error: SSE register return with SSE disabled
 1665 |       min() _GLIBCXX_USE_NOEXCEPT { return __FLT_MIN__; }
      |`   
                                
`/usr/include/c++/9/limits: In static member function ‘static constexpr long double std::numeric_limits<long double>::min()’:`
`/usr/include/c++/9/limits:1815:35: error: x87 register return with x87 disabled
 1815 |       min() _GLIBCXX_USE_NOEXCEPT { return __LDBL_MIN__; }`
